version: '3.8'

services:
  localhost:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: mobilele_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"
    command: ['--character-set-server=utf8mb4','--collation-server=utf8mb4_bin']
