version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_DATABASE: mobilele_db
        - MYSQL_ALLOW_EMPTY_PASSWORD="yes"
    ports:
      - "3306:3306"
    command: ['--character-set-server=utf8mb4','--collation-server=utf8mb4_bin']
